tabs:
  main:
    display: Main
    sections:
      -
        display: Details
        fields:
          -
            handle: role
            field:
              input_type: text
              antlers: true
              type: text
              display: Role
              icon: text
              listable: true
              instructions_position: above
              visibility: computed
              replicator_preview: false
              duplicate: false
              hide_display: false
              always_save: true
          -
            handle: upload_resume
            field:
              max_files: 1
              mode: list
              container: assets
              restrict: true
              allow_uploads: true
              show_filename: true
              show_set_alt: true
              type: assets
              display: 'Upload Resume (PDF or Word doc)'
              instructions: 'Please use only PDFs or Word Documents (.pdf, .doc, .docx)'
              validate:
                - required
              icon: assets
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              folder: resume-submissions
          -
            handle: first_name
            field:
              input_type: text
              antlers: false
              type: text
              display: 'First Name'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: last_name
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Last Name'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: email
            field:
              input_type: email
              antlers: false
              type: text
              display: 'Email address'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
                - email
          -
            handle: phone
            field:
              input_type: tel
              character_limit: 20
              antlers: false
              type: text
              display: 'Phone number'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: linkedin_url
            field:
              input_type: url
              antlers: false
              type: text
              display: 'LinkedIn URL'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: portfolio_url
            field:
              input_type: url
              antlers: false
              type: text
              display: 'Portfolio URL (If applicable)'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: github_url
            field:
              input_type: url
              antlers: false
              type: text
              display: 'GitHub URL (if applicable)'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: other_url
            field:
              input_type: url
              antlers: false
              type: text
              display: 'Other URL (if applicable)'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: university
            field:
              input_type: text
              antlers: false
              type: text
              display: 'University attended'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: highest_education
            field:
              input_type: text
              antlers: false
              type: text
              display: 'What is your highest level of education?'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: current_education_pursuit
            field:
              input_type: text
              antlers: false
              type: text
              display: 'If applicable, what education level are you currently pursuing?'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: graduation_date
            field:
              input_type: date
              antlers: false
              type: text
              display: 'Graduation Date'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: applied_to_scalp_before
            field:
              options:
                'No': null
                'Yes': null
              inline: true
              cast_booleans: false
              type: radio
              display: 'Have you applied for a position at SCALP Trade in the past?'
              icon: radio
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: how_did_you_hear_about_job
            field:
              options:
                Website: null
                'Career Fair': null
                LinkedIn: null
                Glassdoor: null
                'Current or Former employee (see below)': null
                'Other (see below)': null
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: 'How did you hear about this job?'
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: other_or_employee_details
            field:
              input_type: text
              antlers: false
              type: text
              display: 'If seleced "Other" or "Employee" to the above question, please provide those details or employee name below.'
              icon: text
              instructions: "If you selected ‘Other’, or 'Employee' to the question: 'How did you hear about this job?' Please enter name or details below."
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
      -
        display: Authorization
        fields:
          -
            handle: allowed_to_work_in_usa
            field:
              options:
                'No': null
                'Yes': null
              inline: true
              cast_booleans: false
              type: radio
              display: 'Currently, are you legally authorized to work for any employer in the United States of America?'
              icon: radio
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: require_visa_sponsorship
            field:
              options:
                'No': null
                'Yes': null
              inline: true
              cast_booleans: false
              type: radio
              display: 'Will you now or in the future require visa sponsorship to continue working in the United States of America?'
              icon: radio
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: visa_status
            field:
              options:
                'N/A ': null
                'F-1 CPT': null
                'C-1 OPT': null
                'F-1 STEM': null
                H-1B: null
                L-2: null
                E-3: null
                TN: null
                O-1: null
                H1B1: null
                'DACA (Deferred Action for Childhood Arrivals)': null
                'TPS (Temporary Protected Status)': null
                'Family Sponsorship': null
                'No Current Work Authorization': null
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: 'If you answered “Yes” to the question above: What is your current immigration status/basis of your work authorization?'
              icon: select
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: authorization_expiration
            field:
              input_type: date
              antlers: false
              type: text
              display: 'If you have a current work authorization/status, when does it expire? (Please leave blank if you do not require work authorization)'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: sponsorhip_needs_details
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Please provide additional details about your sponsorship needs, current work authorization status, or eligibility for a work authorization status. (Please enter N/A if you do not require work authorization)'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
      -
        display: Submit
        fields:
          -
            handle: all_information_correct
            field:
              options:
                'No': null
                'Yes': null
              inline: true
              cast_booleans: false
              type: radio
              display: 'I certify that all information I have provided in order to apply for this position with SCALP Trade is true, complete, and accurate. I understand further that if any information provided by me is found to be false, misleading, or misrepresented in any respect, that will be sufficient cause to eliminate me from further consideration for employment or may result in my immediate termination, whenever it is discovered.'
              icon: radio
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
