tabs:
  main:
    display: Main
    sections:
      -
        display: Details
        fields:
          -
            handle: role
            field:
              antlers: true
              type: text
              display: Role
              listable: true
              visibility: read_only
              replicator_preview: false
              duplicate: false
              always_save: true
          -
            handle: upload_resume
            field:
              max_files: 1
              container: assets
              restrict: true
              type: assets
              display: 'Upload Resume (PDF or Word doc)'
              instructions: 'Please use only PDFs or Word Documents (.pdf, .doc, .docx)'
              validate:
                - required
              folder: resume-submissions
          -
            handle: first_name
            field:
              type: text
              display: 'First Name'
              validate:
                - required
              placeholder: 'First Name'
          -
            handle: last_name
            field:
              type: text
              display: 'Last Name'
              validate:
                - required
              placeholder: 'Last Name'
          -
            handle: email
            field:
              input_type: email
              type: text
              display: 'Email address'
              validate:
                - required
                - email
              placeholder: careers@scalptrade.com
          -
            handle: phone
            field:
              input_type: tel
              character_limit: 20
              type: text
              display: 'Phone number'
              validate:
                - required
          -
            handle: linkedin_url
            field:
              input_type: url
              type: text
              display: 'LinkedIn URL'
              placeholder: 'https://www.linkedin.com/in/...com'
          -
            handle: portfolio_url
            field:
              input_type: url
              type: text
              display: 'Portfolio URL (If applicable)'
              placeholder: 'https://url...com'
          -
            handle: github_url
            field:
              input_type: url
              type: text
              display: 'GitHub URL (if applicable)'
              placeholder: 'https://github...com'
          -
            handle: other_url
            field:
              input_type: url
              type: text
              display: 'Other URL (if applicable)'
              placeholder: 'https://url...com'
          -
            handle: university
            field:
              type: text
              display: 'University attended'
              placeholder: 'University of ...'
              validate:
                - required
          -
            handle: major
            field:
              type: text
              display: 'University major'
              placeholder: 'Science, Arts, Humanities...'
              validate:
                - required
          -
            handle: highest_education
            field:
              options:
                -
                  key: 'High School Diploma'
                  value: null
                -
                  key: "Associate's"
                  value: null
                -
                  key: "Bachelor's"
                  value: null
                -
                  key: "Master's"
                  value: null
                -
                  key: Doctorate
                  value: null
              type: select
              display: 'Highest level of education or current level of education pursuing'
              validate:
                - required
          -
            handle: graduation_date
            field:
              input_type: date
              type: text
              display: 'Graduation Date'
              validate:
                - required
          -
            handle: applied_to_scalp_before
            field:
              options:
                'No': null
                'Yes': null
              inline: true
              type: radio
              display: 'Have you applied for a position at SCALP Trade in the past?'
              validate:
                - required
          -
            handle: how_did_you_hear_about_job
            field:
              options:
                -
                  key: Website
                  value: null
                -
                  key: 'Career Fair'
                  value: null
                -
                  key: LinkedIn
                  value: null
                -
                  key: Glassdoor
                  value: null
                -
                  key: Handshake
                  value: null
                -
                  key: 'University Job Board'
                  value: null
                -
                  key: 'Current or Former employee (see below)'
                  value: null
                -
                  key: 'Other (see below)'
                  value: null
              type: select
              display: 'How did you hear about this job?'
          -
            handle: other_or_employee_details
            field:
              type: text
              display: 'If seleced "Other" or "Employee" to the above question, please provide those details or employee name.'
              instructions: "If you selected ‘Other’, or 'Employee' to the question: 'How did you hear about this job?' Please enter name or details."
      -
        display: Authorization
        fields:
          -
            handle: allowed_to_work_in_usa
            field:
              options:
                'No': null
                'Yes': null
              inline: true
              type: radio
              display: 'Currently, are you legally authorized to work for any employer in the United States of America?'
              validate:
                - required
          -
            handle: require_visa_sponsorship
            field:
              options:
                'No': null
                'Yes': null
              inline: true
              type: radio
              display: 'Will you now or in the future require visa sponsorship to continue working in the United States of America?'
              validate:
                - required
          -
            handle: visa_status
            field:
              options:
                'N/A ': null
                'F-1 CPT': null
                'C-1 OPT': null
                'F-1 STEM': null
                H-1B: null
                L-2: null
                E-3: null
                TN: null
                O-1: null
                H1B1: null
                'DACA (Deferred Action for Childhood Arrivals)': null
                'TPS (Temporary Protected Status)': null
                'Family Sponsorship': null
                'No Current Work Authorization': null
              type: select
              display: 'If you answered “Yes” to the question above: What is your current immigration status/basis of your work authorization? (Please select N/A if you do not require work authorization)'
              validate:
                - required
          -
            handle: authorization_expiration
            field:
              input_type: date
              type: text
              display: 'If you have a current work authorization/status, when does it expire? (Please leave blank if you do not require work authorization)'
          -
            handle: sponsorhip_needs_details
            field:
              type: text
              display: 'Please provide additional details about your sponsorship needs, current work authorization status, or eligibility for a work authorization status. (Please enter N/A if you do not require work authorization)'
              validate:
                - required
      -
        display: Submit
        fields:
          -
            handle: all_information_correct
            field:
              options:
                'No': null
                'Yes': null
              inline: true
              type: radio
              display: 'I certify that all information I have provided in order to apply for this position with SCALP Trade is true, complete, and accurate. I understand further that if any information provided by me is found to be false, misleading, or misrepresented in any respect, that will be sufficient cause to eliminate me from further consideration for employment or may result in my immediate termination, whenever it is discovered.'
              validate:
                - required
