tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: full_legal_name
            field:
              input_type: text
              placeholder: 'First Middle Last'
              antlers: false
              type: text
              display: 'Full Legal Name'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: email
            field:
              input_type: text
              antlers: false
              type: text
              display: Email
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
                - email
          -
            handle: phone
            field:
              input_type: tel
              character_limit: 20
              antlers: false
              type: text
              display: Phone
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              validate:
                - required
          -
            handle: university
            field:
              input_type: text
              antlers: false
              type: text
              display: University
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: what_is_your_highest_level_of_education
            field:
              input_type: text
              antlers: false
              type: text
              display: 'What is your highest level of education'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: if_applicable_what_education_level_are_you_currently_pursuing
            field:
              input_type: text
              antlers: false
              type: text
              display: 'If applicable, what education level are you currently pursuing'
              icon: text
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: graduation_month
            field:
              options:
                January: null
                February: null
                March: null
                April: null
                May: null
                June: null
                July: null
                August: null
                September: null
                October: null
                November: null
                December: null
              taggable: false
              push_tags: false
              multiple: false
              clearable: false
              searchable: true
              cast_booleans: false
              type: select
              display: 'Graduation Month'
              icon: select
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: year
            field:
              type: integer
              display: Year
              icon: integer
              width: 50
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: have_you_applied_for_a_position_at_scalp_trade_in_the_past
            field:
              options:
                'No': null
                'Yes': null
              inline: false
              cast_booleans: false
              type: radio
              display: 'Have you applied for a position at SCALP Trade in the past'
              icon: radio
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
